
name: app-dev   

replicaCount: 1

image:
  repository: ahmed20007/app  
  tag: latest

service:
  type: ClusterIP
  port: 8080        

ingress:
  enabled: true
  host: localhost
  class: nginx

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuTarget: 50

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

imagePullSecrets:
  - name: regcred    
