replicaCount: 3

image:
  repository: app
  tag: "main"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  host: app.example.com

hpa:
  minReplicas: 3
  maxReplicas: 10
  cpuTarget: 70
