---
- name: Setup CI Runner tools
  hosts: ci_runner
  become: yes
  tasks:

    - name: Install prerequisites
      apt:
        name:
          - curl
          - unzip
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes
        cache_valid_time: 3600  # cache valid for 1 hour



    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Install Terraform
      shell: |
        curl -LO https://releases.hashicorp.com/terraform/1.8.8/terraform_1.8.8_linux_amd64.zip
        unzip -o terraform_1.8.8_linux_amd64.zip -d /usr/local/bin/
      args:
        creates: /usr/local/bin/terraform

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install
      args:
        creates: /usr/local/bin/aws

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
